# Generated by Django 4.1.1 on 2022-10-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(choices=[('Pizzas', 'Pizzas'), ('Massas', 'Massas'), ('Salgados', 'Salgados'), ('Bolos', 'Bolos'), ('Tortas', 'Tortas'), ('Pão Caseiro', 'Pão Caseiro')], default='category', max_length=20)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
