# Generated by Django 4.1.1 on 2022-10-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='description',
        ),
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='modo_de_preparo',
            field=models.TextField(null=True),
        ),
    ]
