# Generated by Django 4.1.2 on 2022-10-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
