# Generated by Django 6.0.3 on 2026-03-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='category',
            field=models.CharField(choices=[('Pizzas', 'Pizzas'), ('Massas', 'Massas'), ('Salgados', 'Salgados'), ('Bolos', 'Bolos'), ('Tortas', 'Tortas'), ('Pão Caseiro', 'Pão Caseiro')], default='Massas', max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='modo_de_preparo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
