# Generated by Django 6.0.3 on 2026-03-11 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_alter_receita_category_alter_receita_ingredientes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'ordering': ['-created_at'], 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AddField(
            model_name='receita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/'),
        ),
        migrations.AddField(
            model_name='receita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
