# Generated by Django 4.1.2 on 2022-10-19 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_created_at_receita_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='modo_de_preparo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
