# Generated by Django 4.1.2 on 2022-10-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receita_created_at_alter_receita_ingredientes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
